version: "3.7"

services: 
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://alex:postgres@localhost:5432/reddit?schema=public
      - AUTH-SECRET=secret
      - PORT=8080
    command: npm start
    depends_on:
      - db
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=reddit
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"